In [12]:
import os
import joblib
import pandas as pd
import numpy as np

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    StratifiedKFold
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [13]:
DATA_PATH = "../dataset/UNSW_NB15_testing-set.parquet"

dataset = pd.read_parquet(DATA_PATH)

print(dataset.shape)
dataset.head()

(82332, 36)

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.000011,udp,-,INT,2,0,496,0,90909.09375,180363632.0,...,0,0,1,1,0,0,0,0,Normal,0
1,0.000008,udp,-,INT,2,0,1762,0,125000.00000,881000000.0,...,0,0,1,1,0,0,0,0,Normal,0
2,0.000005,udp,-,INT,2,0,1068,0,200000.00000,854400000.0,...,0,0,1,1,0,0,0,0,Normal,0
3,0.000006,udp,-,INT,2,0,900,0,166666.65625,600000000.0,...,0,0,2,1,0,0,0,0,Normal,0
4,0.000010,udp,-,INT,2,0,2126,0,100000.00000,850400000.0,...,0,0,2,1,0,0,0,0,Normal,0

In [14]:
LIVE_FEATURES = [
    "dur",
    "proto",
    "spkts",
    "dpkts",
    "sbytes",
    "dbytes",
    "rate",
    "sload",
    "dload",
    "sinpkt",
    "dinpkt",
    "smean",
    "dmean"
]

X = dataset[LIVE_FEATURES].copy()
y = dataset["label"].copy()

print(X.shape)
print(y.value_counts())

(82332, 13)
label
1    45332
0    37000
Name: count, dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (65865, 13)
Testing: (16467, 13)

In [16]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "proto_encoder",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            ["proto"]
        )
    ],
    remainder="passthrough"
)

In [17]:
rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("rf", rf)
])

In [18]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [19]:
param_grid = {

    "rf__n_estimators": [
        100,
        200,
        300
    ],

    "rf__max_depth": [
        10,
        20,
        30,
        None
    ],

    "rf__min_samples_split": [
        2,
        5,
        10
    ],

    "rf__min_samples_leaf": [
        1,
        2,
        4
    ],

    "rf__max_features": [
        "sqrt",
        "log2"
    ],

    "rf__class_weight": [
        None,
        "balanced"
    ]
}

In [20]:
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring="f1",
    cv=cv,
    n_jobs=-1,
    verbose=2,
    return_train_score=True
)

In [21]:
grid_search.fit(
    X_train,
    y_train
)

Fitting 5 folds for each of 432 candidates, totalling 2160 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('proto_encoder',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         ['proto'])])),
                                       ('rf',
                                        RandomForestClassifier(n_jobs=-1,
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'rf__class_weight': [None, 'balanced'],
                         'rf__max_depth': [10, 20, 30, None],
                         'rf__max_features': ['sqrt', 'log2'],
                         'rf__min_samples_leaf': [1, 2, 4],
                         'rf__min_samples_split': [2, 5, 10],
                         'rf__n_estimators': [100, 200, 300]},
             return_train_score=True, scoring='f1', verbose=2)

In [27]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

print("TEST RESULTS")
print("-------------------------")
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

TEST RESULTS
-------------------------
Accuracy : 0.9340499180178539
Precision: 0.9608499826769835
Recall   : 0.9176133230395941
F1 Score : 0.9387340629583663

Confusion Matrix:
[[7061  339]
 [ 747 8320]]

In [22]:
print(
    "Best CV F1:",
    grid_search.best_score_
)

print("\nBest Parameters:")

for parameter, value in grid_search.best_params_.items():
    print(parameter, ":", value)

Best CV F1: 0.9409222828047923

Best Parameters:
rf__class_weight : balanced
rf__max_depth : None
rf__max_features : sqrt
rf__min_samples_leaf : 1
rf__min_samples_split : 5
rf__n_estimators : 100

In [23]:
best_pipeline = grid_search.best_estimator_

y_pred = best_pipeline.predict(
    X_test
)

print(
    "Accuracy:",
    accuracy_score(y_test, y_pred)
)

print(
    "Precision:",
    precision_score(y_test, y_pred)
)

print(
    "Recall:",
    recall_score(y_test, y_pred)
)

print(
    "F1:",
    f1_score(y_test, y_pred)
)

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred
    )
)

print("\nConfusion Matrix:")

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

Accuracy: 0.9340499180178539
Precision: 0.9608499826769835
Recall: 0.9176133230395941
F1: 0.9387340629583663

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.93      7400
           1       0.96      0.92      0.94      9067

    accuracy                           0.93     16467
   macro avg       0.93      0.94      0.93     16467
weighted avg       0.94      0.93      0.93     16467


Confusion Matrix:
[[7061  339]
 [ 747 8320]]

In [24]:
best_preprocessor = (
    best_pipeline.named_steps[
        "preprocessor"
    ]
)

best_rf = (
    best_pipeline.named_steps[
        "rf"
    ]
)

In [25]:
TUNED_DIR = "../models/tuned"

os.makedirs(
    TUNED_DIR,
    exist_ok=True
)

joblib.dump(
    best_rf,
    os.path.join(
        TUNED_DIR,
        "tuned_random_forest.pkl"
    )
)

joblib.dump(
    best_preprocessor,
    os.path.join(
        TUNED_DIR,
        "tuned_preprocessor.pkl"
    )
)

print(
    "Tuned model saved successfully"
)

Tuned model saved successfully

In [26]:
results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    "Old RF": [
        0.9336,
        0.9555,
        0.9224,
        0.9387
    ],

    "Tuned RF": [
        accuracy_score(y_test, y_pred),
        precision_score(y_test, y_pred),
        recall_score(y_test, y_pred),
        f1_score(y_test, y_pred)
    ]
})

results

      Metric  Old RF  Tuned RF
0   Accuracy  0.9336  0.934050
1  Precision  0.9555  0.960850
2     Recall  0.9224  0.917613
3   F1 Score  0.9387  0.938734

In [28]:
import os
import joblib

os.makedirs("../models/tuned", exist_ok=True)

joblib.dump(
    best_model,
    "../models/tuned/tuned_rf_pipeline.pkl"
)

print("Tuned model saved successfully")

Tuned model saved successfully